### ISSUE TITLE
Error when running on video file

### ISSUE THREAD

**Issue by fepegar** [philipNoonan/pyglFaceBlur#2]
I installed this package from my fork:

```shell
pip install -U git+https://github.com/fepegar/pyglFaceBlur@fix-packaging
```

It worked great from the camera, but I got an error when trying a file:

```python-traceback
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

Traceback (most recent call last):
  File "/home/fernando/miniconda3/envs/test/bin/pyglfaceblur", line 8, in <module>
    sys.exit(main())
  File "/home/fernando/miniconda3/envs/test/lib/python3.8/site-packages/pyglfaceblur/face_blur.py", line 238, in main
    writer = cv2.VideoWriter('.//output.wmv', fourcc, 20.0, (width,  height), True)
cv2.error: OpenCV(4.5.2) :-1: error: (-5:Bad argument) in function 'VideoWriter'
> Overload resolution failed:
>  - Can't parse 'frameSize'. Sequence item with index 0 has a wrong type
>  - Argument 'fourcc' is required to be an integer
>  - Can't parse 'frameSize'. Sequence item with index 0 has a wrong type
>  - VideoWriter() missing required argument 'params' (pos 6)
```

It's an MKV. Does it have to be any specific extension?

**Comment by fepegar** [comment]
By the way, this is Ubuntu 18.04.

**Comment by philipNoonan** [comment]
Ah yeah, videowriter requires ints and was being given floats, so obvs it just refused to work with that garbage. Fixed now!
